my_list=[3,1,2,4]
my_list.sort()
print(my_list)
my_list=["banana","apple","cherry"]
my_list.sort(reverse=True)
print(my_list)
my_list=[3,1,2,4]
sorted_list=sorted(my_list)
print(sorted_list)
print(my_list)
